CONFIG_PRINTK=y

CONFIG_MULTITHREADING=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_MONITOR=y
CONFIG_MAIN_STACK_SIZE=2048

CONFIG_DYNAMIC_THREAD=y
CONFIG_DYNAMIC_THREAD_STACK_SIZE=2048

CONFIG_ENABLE_THREADS_TEST=y
CONFIG_STATIC_THREAD_TEST=y
CONFIG_DYNAMIC_THREAD_TEST=y # override STATIC_THREAD_TEST
CONFIG_THREAD_SUSPEND_RESUME_TEST=y # override DYNAMIC_THREAD_TEST
CONFIG_THREAD_PREEMTION_TEST=y # override SUSPEND_RESUME_TEST
CONFIG_THREAD_YIELDING_TEST=y # override PREEMPTION_TEST