CONFIG_PRINTK=y
CONFIG_EVENTS=y

# choices (one active at a time)
CONFIG_WAIT_ANY_LOGIC=y
CONFIG_WAIT_ALL_LOGIC=y
CONFIG_ONE_SRC_MANY_MONITORS_NO_CLEAR_BIT=y
CONFIG_ONE_SRC_MANY_MONITORS_WITH_CLEAR_BIT=y
