CONFIG_LOG=y
CONFIG_PRINTK=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

# log levels (0=none, 1=error, 2=warning, 3=info, 4=debug)
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_LOG_BUFFER_SIZE=1024
CONFIG_LOG_TIMESTAMP_64BIT=y
CONFIG_LOG_BACKEND_SHOW_COLOR=y

CONFIG_LOG_MODE_IMMEDIATE=y