#ifndef CASTLE_UTILITY_TUPLE_H
#define CASTLE_UTILITY_TUPLE_H

#include "castle/core/compiler.h"
#include "castle/core/error_handler.h"
#include "castle/core/types.h"
#include "castle/core/traits.h"
#include "castle/utility/integral_sequence.h"
#include "castle/utility/move.h"
#include "castle/utility/forward.h"

namespace castle
{

template <typename... Ts>
class tuple;

// ============================================================================
// tuple_element
//
// Maps a tuple index to its corresponding element type.
//
// Example:
//
//     tuple_element_t<0, tuple<int, float>>  -> int
//     tuple_element_t<1, tuple<int, float>>  -> float
// ============================================================================

template <size_type Index, typename Tuple>
struct tuple_element;

template <size_type Index, typename Head, typename... Tail>
struct tuple_element<Index, castle::tuple<Head, Tail...>>
    : tuple_element<Index - 1U, castle::tuple<Tail...>>
{
};

template <typename Head, typename... Tail>
struct tuple_element<0U, castle::tuple<Head, Tail...>>
{
    using type = Head;
};

template <size_type Index, typename Tuple>
using tuple_element_t = typename tuple_element<Index, Tuple>::type;

// ============================================================================
// tuple_size
// ============================================================================

template <typename Tuple>
struct tuple_size;

template <typename... Ts>
struct tuple_size<castle::tuple<Ts...>>
    : integral_constant<size_type, sizeof...(Ts)>
{
};

namespace detail
{

// ============================================================================
// detail::tuple_leaf
//
// Stores one tuple element.
//
// The index is part of the type, allowing tuples containing duplicate types:
//
//     tuple<int, int, int>
//
// to store all three elements independently.
// ============================================================================

template <size_type Index, typename T>
struct tuple_leaf
{
    T value;

    CASTLE_CONSTEXPR tuple_leaf()
        : value()
    {
    }

    template <typename U>
    CASTLE_CONSTEXPR explicit tuple_leaf(U&& other)
        : value(CASTLE_FORWARD<U>(other))
    {
    }
};

// ============================================================================
// detail::tuple_impl
//
// Expands:
//
//     tuple<int, float, uint8_t>
//
// into:
//
//     tuple_leaf<0, int>
//     tuple_leaf<1, float>
//     tuple_leaf<2, uint8_t>
// ============================================================================

template <typename Sequence, typename... Ts>
struct tuple_impl;

template <size_type... Indices, typename... Ts>
struct tuple_impl<sequence::index_sequence<Indices...>,
    Ts...>
    : tuple_leaf<Indices, Ts>...
{
    CASTLE_CONSTEXPR tuple_impl()
        : tuple_leaf<Indices, Ts>()...
    {
    }

    template <typename... Us>
    CASTLE_CONSTEXPR explicit tuple_impl(Us&&... values)
        : tuple_leaf<Indices, Ts>(
              CASTLE_FORWARD<Us>(values))...
    {
    }
};

} // namespace detail

// ============================================================================
// tuple
//
// Fixed-size heterogeneous aggregate.
//
// Properties:
//
// - No dynamic allocation.
// - No STL dependency.
// - No virtual functions.
// - No RTTI.
// - No exceptions generated by CASTLE itself.
// - Compile-time element indexing.
// - Supports duplicate element types.
// - C++17 compatible.
// ============================================================================

template <typename... Ts>
class tuple
    : public detail::tuple_impl<
          sequence::index_sequence_for<Ts...>,
          Ts...>
{
private:

    using base_type =
        detail::tuple_impl<
            sequence::index_sequence_for<Ts...>,
            Ts...>;

public:

    using size_type = castle::size_type;

    // Number of elements in the tuple.
    static CASTLE_CONSTEXPR size_type size() CASTLE_NOEXCEPT
    {
        return sizeof...(Ts);
    }

    // Default construction.
    //
    // This is available only when all element types are default constructible.
    CASTLE_CONSTEXPR tuple() CASTLE_DEFAULT;

    // Construct all tuple elements from the supplied arguments.
    //
    // The number of arguments must exactly match the number of tuple elements.
    template <
        typename... Us,
        typename meta::enable_if<
            sizeof...(Us) == sizeof...(Ts),
            int>::type = 0>
    CASTLE_CONSTEXPR explicit tuple(Us&&... values)
        : base_type(CASTLE_FORWARD<Us>(values)...)
    {
    }

    // Default copy/move operations are intentional.
    tuple(CASTLE_CONST tuple&) CASTLE_DEFAULT;
    tuple(tuple&&) CASTLE_DEFAULT;

    tuple& operator=(CASTLE_CONST tuple&) CASTLE_DEFAULT;
    tuple& operator=(tuple&&) CASTLE_DEFAULT;

    ~tuple() CASTLE_DEFAULT;
};


// ============================================================================
// get<I>()
//
// Access tuple element by compile-time index.
//
// Example:
//
//     tuple<int, float> value{10, 3.14F};
//
//     get<0>(value);
//     get<1>(value);
// ============================================================================

template <size_type Index, typename... Ts>
CASTLE_CONSTEXPR
castle::tuple_element_t<Index, tuple<Ts...>>&
get(tuple<Ts...>& value) CASTLE_NOEXCEPT
{
    using value_type = castle::tuple_element_t<Index, tuple<Ts...>>;
    using leaf_type = detail::tuple_leaf<Index, value_type>;

    return static_cast<leaf_type&>(value).value;
}


template <size_type Index, typename... Ts>
CASTLE_CONSTEXPR
CASTLE_CONST castle::tuple_element_t<Index, tuple<Ts...>>&
get(CASTLE_CONST tuple<Ts...>& value) CASTLE_NOEXCEPT
{
    using value_type = castle::tuple_element_t<Index, tuple<Ts...>>;
    using leaf_type = detail::tuple_leaf<Index, value_type>;

    return static_cast<CASTLE_CONST leaf_type&>(value).value;
}


template <size_type Index, typename... Ts>
CASTLE_CONSTEXPR
castle::tuple_element_t<Index, tuple<Ts...>>&&
get(tuple<Ts...>&& value) CASTLE_NOEXCEPT
{
    return CASTLE_MOVE(get<Index>(value));
}


template <size_type Index, typename... Ts>
CASTLE_CONSTEXPR
CASTLE_CONST castle::tuple_element_t<Index, tuple<Ts...>>&&
get(CASTLE_CONST tuple<Ts...>&& value) CASTLE_NOEXCEPT
{
    return CASTLE_MOVE(get<Index>(value));
}


// ============================================================================
// tuple_type_count
//
// Counts how many times T appears in Ts...
//
// This is used by get<T>() to enforce the tuple requirement that T must occur
// exactly once.
// ============================================================================

namespace meta
{

template <typename T, typename... Ts>
struct tuple_type_count;

template <typename T>
struct tuple_type_count<T>
    : castle::integral_constant<size_type, 0U>
{
};

template <typename T, typename Head, typename... Tail>
struct tuple_type_count<T, Head, Tail...>
    : castle::integral_constant<
          size_type,
          (castle::is_same<T, Head>::value ? 1U : 0U)
              + tuple_type_count<T, Tail...>::value>
{
};


// ============================================================================
// tuple_type_index
//
// Finds the first index of T.
//
// This trait is intended to be used only after tuple_type_count<T, Ts...>
// has established that T occurs exactly once.
// ============================================================================

template <typename T, typename... Ts>
struct tuple_type_index;

template <typename T, typename Head, typename... Tail>
struct tuple_type_index<T, Head, Tail...>
{
    static CASTLE_CONSTEXPR size_type value =
        castle::is_same<T, Head>::value
            ? 0U
            : 1U + tuple_type_index<T, Tail...>::value;
};

template <typename T>
struct tuple_type_index<T>
{
    static CASTLE_CONSTEXPR size_type value = 0U;
};

} // namespace meta


// ============================================================================
// get<T>()
//
// Access tuple element by unique type.
//
// Example:
//
//     tuple<int, float> value{10, 3.14F};
//
//     get<int>(value);
//     get<float>(value);
//
// T must occur exactly once in the tuple.
// ============================================================================

template <typename T, typename... Ts>
CASTLE_CONSTEXPR T&
get(tuple<Ts...>& value) CASTLE_NOEXCEPT
{
    static_assert(
        meta::tuple_type_count<T, Ts...>::value == 1U,
        "castle::get<T> requires T to occur exactly once in tuple"
    );

    return castle::get<meta::tuple_type_index<T, Ts...>::value>(value);
}


template <typename T, typename... Ts>
CASTLE_CONSTEXPR CASTLE_CONST T&
get(CASTLE_CONST tuple<Ts...>& value) CASTLE_NOEXCEPT
{
    static_assert(
        meta::tuple_type_count<T, Ts...>::value == 1U,
        "castle::get<T> requires T to occur exactly once in tuple"
    );

    return castle::get<meta::tuple_type_index<T, Ts...>::value>(value);
}


template <typename T, typename... Ts>
CASTLE_CONSTEXPR T&&
get(tuple<Ts...>&& value) CASTLE_NOEXCEPT
{
    static_assert(
        meta::tuple_type_count<T, Ts...>::value == 1U,
        "castle::get<T> requires T to occur exactly once in tuple"
    );

    return castle::get<
        meta::tuple_type_index<T, Ts...>::value>(
            CASTLE_MOVE(value));
}


template <typename T, typename... Ts>
CASTLE_CONSTEXPR CASTLE_CONST T&&
get(CASTLE_CONST tuple<Ts...>&& value) CASTLE_NOEXCEPT
{
    static_assert(
        meta::tuple_type_count<T, Ts...>::value == 1U,
        "castle::get<T> requires T to occur exactly once in tuple"
    );

    return castle::get<
        meta::tuple_type_index<T, Ts...>::value>(
            CASTLE_MOVE(value));
}


// ============================================================================
// tuple_size_v
// ============================================================================

template <typename Tuple>
inline CASTLE_CONSTEXPR size_type tuple_size_v = castle::tuple_size<Tuple>::value;


// ============================================================================
// tuple_element_t
//
// Public convenience alias.
//
// Example:
//
//     castle::tuple_element_t<0, castle::tuple<int, float>>
//         -> int
// ============================================================================

template <size_type Index, typename Tuple>
using tuple_element_t = typename castle::tuple_element<Index, Tuple>::type;


// ============================================================================
// make_tuple
//
// Creates a tuple whose element types are decay_t<Ts>.
//
// Example:
//
//     auto value = castle::make_tuple(10, 3.14F);
//
//     // value is tuple<int, float>
// ============================================================================

template <typename... Ts>
CASTLE_CONSTEXPR
tuple<castle::decay_t<Ts>...>
make_tuple(Ts&&... values)
{
    return tuple<castle::decay_t<Ts>...>(CASTLE_FORWARD<Ts>(values)...);
}


// ============================================================================
// tie
//
// Creates a tuple of lvalue references.
//
// Example:
//
//     int id;
//     float value;
//
//     auto references = castle::tie(id, value);
//
//     get<0>(references) = 42;
// ============================================================================

template <typename... Ts>
CASTLE_CONSTEXPR
tuple<Ts&...>
tie(Ts&... values) CASTLE_NOEXCEPT
{
    return tuple<Ts&...>(values...);
}


// ============================================================================
// ignore
//
// Assignment sink used with tuple-like unpacking.
//
// Example:
//
//     int id;
//     int status;
//
//     auto result = castle::tuple<int, int>{10, 20};
//
//     castle::tie(id, castle::ignore) = result;
//
// The assignment operator intentionally does nothing.
// ============================================================================

struct ignore_t
{
    template <typename T>
    CASTLE_CONSTEXPR
    ignore_t& operator=(T&&) CASTLE_NOEXCEPT
    {
        return *this;
    }
};

inline ignore_t ignore{};


// ============================================================================
// forward_as_tuple
//
// Creates a tuple of forwarding references without copying the values.
//
// This is useful as an intermediate representation for generic code.
//
// Example:
//
//     auto args = castle::forward_as_tuple(a, CASTLE_MOVE(b));
// ============================================================================

template <typename... Ts>
CASTLE_CONSTEXPR
tuple<Ts&&...>
forward_as_tuple(Ts&&... values) CASTLE_NOEXCEPT
{
    return tuple<Ts&&...>(CASTLE_FORWARD<Ts>(values)...);
}

} // namespace castle

#endif // CASTLE_UTILITY_TUPLE_H