CONFIG_PRINTK=y
CONFIG_MULTITHREADING=y
CONFIG_POLL=y
CONFIG_HEAP_MEM_POOL_SIZE=2048

CONFIG_BASIC_WORK_QUEUE_TEST=y
CONFIG_WORK_QUEUE_DELAY_TEST=y
CONFIG_WORK_QUEUE_POLL_TEST=y
CONFIG_CONTAINER_OF_TEST=y
CONFIG_ADDITIONAL_WORK_QUEUE_TEST=y
CONFIG_WORK_QUEUE_SYNC_TEST=y