CONFIG_CPP=y
CONFIG_STD_CPP17=y

CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_CPP_RTTI=y
CONFIG_CPP_EXCEPTIONS=y

CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_NANO=n

# Allocate a 64KB global heap memory pool for dynamic allocations
CONFIG_HEAP_MEM_POOL_SIZE=65536

# Recommended: Expand stack sizes to prevent overflows caused by heavy exception frames
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
