#ifndef CASTLE_CORE_COMPILER_VARIANTS_DEFAULT_H
#define CASTLE_CORE_COMPILER_VARIANTS_DEFAULT_H

#define CASTLE_COMPILER_UNKNOWN 1

#define CASTLE_INLINE           inline
#define CASTLE_HOT
#define CASTLE_COLD
#define CASTLE_NOINLINE

#define CASTLE_LIKELY(x)        (x)
#define CASTLE_UNLIKELY(x)      (x)

#define CASTLE_UNREACHABLE()    ((void)0)

#define CASTLE_PACKED_ATTR
#define CASTLE_RESTRICT

#endif // CASTLE_CORE_COMPILER_VARIANTS_DEFAULT_H
